name: webpack
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_boxicons: ^3.2.0
  url_launcher: ^6.3.1
  flutter_map: ^6.1.0 
  latlong2: ^0.9.0
  delayed_display: ^2.0.0
  video_player_web: ^2.3.4
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - lib/src/img/
      - lib/src/img/home/
      - lib/src/img/support/
      - lib/src/img/us/
      - lib/src/pdf/support/
      - lib/src/videos/catalog/
      - lib/src/videos/
      - lib/src/img/smartbag/
      - lib/src/img/ecobag/
      - lib/tool/
      
      
  fonts:
    - family: D-DINExp
      fonts:
        - asset: lib/src/fonts/D-DINExp.ttf
        - asset: lib/src/fonts/D-DINExp-Bold.ttf
  