name: webpack
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_boxicons: ^3.2.0
  url_launcher: ^6.3.1
  latlong2: ^0.9.0
  delayed_display: ^2.0.0
  flutter_3d_controller: ^2.2.0
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/img/
      - assets/img/3DM/EcoBag/4PRO/
      - assets/img/3DM/EcoBag/5PRO/
      - assets/img/3DM/EcoBag/Doypack/
      - assets/img/3DM/EcoBag/Flowpack/
      - assets/img/3DM/SmartBag/4PRO/
      - assets/img/3DM/SmartBag/5PRO/
      - assets/img/3DM/SmartBag/Doypack/
      - assets/img/3DM/SmartBag/Flowpack/
      - assets/img/3DM/SmartBag/Standpack/
      - assets/img/home/
      - assets/img/ecobag/
      - assets/img/smartbag/
      - assets/img/support/
      - assets/img/us/
      - assets/fonts/
      - lib/src/gifts/
      - lib/src/videos/
      - lib/src/videos/us/
      - lib/src/videos/ecobag/
      
      
  fonts:
    - family: D-DINExp
      fonts:
        - asset: assets/fonts/D-DINExp.ttf
        - asset: assets/fonts/D-DINExp-Bold.ttf
  