name: webpack
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_boxicons: ^3.2.0
  url_launcher: ^6.3.1
  flutter_3d_controller: ^2.2.0
  provider: ^6.1.4
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  collection: ^1.19.1
  visibility_detector: ^0.4.0+2
  carousel_slider: ^5.1.1
  animated_text_kit: ^4.2.3
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # Modelos
    - assets/3Dmodels/
    - assets/3Dmodels/4PRO/
    - assets/3Dmodels/4PRO/Barroco/
    - assets/3Dmodels/4PRO/Bella/
    - assets/3Dmodels/4PRO/Cobriza/
    - assets/3Dmodels/4PRO/Costal/
    - assets/3Dmodels/4PRO/Decembrina/
    - assets/3Dmodels/4PRO/Envejecida/
    - assets/3Dmodels/4PRO/Fuelle_dorado/
    - assets/3Dmodels/4PRO/Grano_café/
    - assets/3Dmodels/4PRO/Kraft/
    - assets/3Dmodels/4PRO/Negra_flor_de_café/
    - assets/3Dmodels/4PRO/Odre/
    - assets/3Dmodels/4PRO/Pastel/
    - assets/3Dmodels/4PRO/Rosa_de_Sharon/
    - assets/3Dmodels/4PRO/Visos_dorados/
    - assets/3Dmodels/5PRO/
    - assets/3Dmodels/5PRO/Barroco/
    - assets/3Dmodels/5PRO/Bottom_flores/
    - assets/3Dmodels/5PRO/Unicolor/
    - assets/3Dmodels/DOYPACK/
    - assets/3Dmodels/DOYPACK/Grano_café/
    - assets/3Dmodels/DOYPACK/Unicolor/
    - assets/3Dmodels/FLOWPACK/
    - assets/3Dmodels/STANDPACK/
    - assets/3Dmodels/STANDPACK/Fruta/
    - assets/3Dmodels/STANDPACK/Pollo/
    # Imagenes
    - assets/img/
    - assets/img/3DM/EcoBag/4PRO/
    - assets/img/3DM/EcoBag/5PRO/
    - assets/img/3DM/EcoBag/Doypack/
    - assets/img/3DM/EcoBag/Flowpack/
    - assets/img/3DM/SmartBag/4PRO/
    - assets/img/3DM/SmartBag/5PRO/
    - assets/img/3DM/SmartBag/Doypack/
    - assets/img/3DM/SmartBag/Flowpack/
    - assets/img/3DM/SmartBag/Standpack/
    - assets/img/home/
    - assets/img/ecobag/
    - assets/img/ecobag/4pro/
    - assets/img/ecobag/5pro/
    - assets/img/ecobag/doypack/
    - assets/img/smartbag/
    - assets/img/smartbag/clipart/
    - assets/img/smartbag/4pro/
    - assets/img/smartbag/4pro/frames/
    - assets/img/smartbag/doypack/
    - assets/img/smartbag/5pro/
    - assets/img/smartbag/flowpack/
    - assets/img/smartbag/piramidal/
    - assets/img/smartbag/cojin/
    - assets/img/smartbag/standpack/
    - assets/img/support/
    - assets/img/us/
    # Fuentes
    - assets/fonts/
    # PDF's
    - assets/pdf/
    # Gifts
    - assets/gifts/
    # Videos
    - assets/videos/
    - assets/videos/ecobag/
    - assets/videos/smartbag/
    - assets/videos/smartbag/4pro/
    - assets/videos/smartbag/5pro/
    - assets/videos/smartbag/doypack/
    - assets/videos/smartbag/flowpack/
    - assets/videos/smartbag/piramidal/
    - assets/videos/smartbag/cojin/
    - assets/videos/smartbag/standpack/
    - assets/videos/ecobag/4pro/
    - assets/videos/us/
      
      
  fonts:
    - family: D-DINExp
      fonts:
        - asset: assets/fonts/D-DINExp.ttf
        - asset: assets/fonts/D-DINExp-Bold.ttf
  