name: webpack
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - lib/src/img/
  fonts:
    - family: D-DINExp
      fonts:
        - asset: lib/src/fonts/D-DINExp.ttf
        - asset: lib/src/fonts/D-DINExp-Bold.ttf
  