final Map<String, List<String>> routeImagePreloads = {
  '/': [
    'img/home/asesoria.webp',
    'img/home/calidad.webp',
    'img/home/cumplimiento.webp',
    'img/home/eco.webp',
    'img/home/home1.webp',
    'img/home/mosquera.webp',
    'img/home/norte.webp',
    'img/home/packvision.webp',
    'img/home/servicios.webp',
    'img/home/smart.webp',
    'img/home/whypk.jpg',
  ],
  '/SmartBag': [],
  '/EcoBag': ['img/ecobag/hoja1.webp', 'img/ecobag/hoja2.webp', 'img/ecobag/hoja3.webp'],

  '/SmartBag/Explora-SmartBag/4PRO': [
    'img/smartbag/4pro.webp',
    'img/smartbag/4pro/cuatrilamina.webp',
    'img/smartbag/4pro/down.webp',
    'img/smartbag/4pro/peel.webp',
    'img/smartbag/4pro/prueba.webp',
    'img/smartbag/4pro/terminacion.webp',
    'img/smartbag/4pro/top.webp',
    'img/smartbag/4pro/valvulas.webp',
  ],
  '/SmartBag/Explora-SmartBag/5PRO': [
    'img/smartbag/5pro/5proStart.webp',
    'img/smartbag/5pro/bags.webp',
    'img/smartbag/5pro/cardmin2.webp',
    'img/smartbag/5pro/cardmin3.webp',
    'img/smartbag/5pro/cardmin4.webp',
    'img/smartbag/5pro/cardmin5.webp',
    'img/smartbag/5pro/earth.webp',
    'img/smartbag/5pro/large.webp',
    'img/smartbag/5pro/prueba.webp',
    'img/smartbag/5pro/saturn.webp',
  ],
  '/SmartBag/Explora-SmartBag/Doypack': [
    'img/smartbag/doypack/inicio.webp',
    'img/smartbag/doypack/3ventanas.webp',
    'img/smartbag/doypack/aloneBag.webp',
    'img/smartbag/doypack/aloneBag2.webp',
    'img/smartbag/doypack/bag_finally.webp',
    'img/smartbag/doypack/twobags1.webp',
    'img/smartbag/doypack/twobags2.webp',
    'img/WImagotipo.webp',
  ],

  '/SmartBag/Explora-SmartBag/Flowpack': [
    'img/smartbag/flowpack/colorAzul.webp',
    'img/smartbag/flowpack/colorBlanco.webp',
    'img/smartbag/flowpack/ColorDorado.webp',
    'img/smartbag/flowpack/colorMetalizada.webp',
    'img/smartbag/flowpack/colorNaranja.webp',
    'img/smartbag/flowpack/colorNaranjaLechosa.webp',
    'img/smartbag/flowpack/ColorNegro.webp',
    'img/smartbag/flowpack/colorRojo.webp',
    'img/smartbag/flowpack/cortina.webp',
    'img/smartbag/flowpack/cruzado.webp',
    'img/smartbag/flowpack/flowpack_blanco.webp',
    'img/smartbag/flowpack/flowpackBlancoNegro.webp',
    'img/smartbag/flowpack/flowpackVs4proBlancoNegro.webp',
    'img/smartbag/flowpack/inicio.webp',
    'img/smartbag/flowpack/perlas.webp',
    'img/smartbag/flowpack/splash.webp',
  ],

  '/SmartBag/Especiales-SmartBag/Piramidal': ['img/smartbag/piramidal/BIG.webp', 'img/smartbag/piramidal/end.webp'],
  '/SmartBag/Especiales-SmartBag/Cojin': ['img/smartbag/cojin/Big.webp', 'img/smartbag/cojin/end.webp', 'img/smartbag/cojin/inicio.webp'],
  '/SmartBag/Especiales-SmartBag/Standpack': [
    'img/smartbag/standpack/big.webp',
    'img/smartbag/standpack/end.webp',
    'img/smartbag/standpack/inicio.webp',
  ],

  '/EcoBag/Explora-EcoBag/4PRO': [
    'img/ecobag/4pro/Bags.webp',
    'img/ecobag/4pro/barroco_Natural.webp',
    'img/ecobag/4pro/end.webp',
    'img/ecobag/4pro/grano_cafe.webp',
    'img/ecobag/4pro/inicio.webp',
    'img/ecobag/4pro/Kraft_Blanco.webp',
    'img/ecobag/4pro/Kraft_natural.webp',
    'img/ecobag/4pro/Kraft_negro.webp',
    'img/ecobag/4pro/Kraft_rojo.webp',
    'img/ecobag/4pro/Kraft_verde.webp',
    'img/ecobag/4pro/peel_y_valv.webp',
    'img/ecobag/4pro/twoBags.webp',
  ],
  '/EcoBag/Explora-EcoBag/5PRO': [
    'img/ecobag/5pro/bags.webp',
    'img/ecobag/5pro/frames/frame0041.webp',
    'img/ecobag/5pro/frames/frame0072.webp',
    'img/ecobag/5pro/frames/frame0106.webp',
    'img/ecobag/5pro/frames/frame0199.webp',
    'img/ecobag/5pro/inicio.webp',
    'img/ecobag/5pro/end.webp',
  ],
};
